# Site wide configuration

title: Rachel Xiang
description: A blog about
logo: # 120x120 px default image used for Twitter summary card
teaser: divider.png
locale:
url: # rdxiang.github.io

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Rachel Xiang
  email: rachelxiang@gmail.com
  twitter: rachelxiang
  # google:
  #   ad-client: 
  #   ad-slot:  
  bio: "Fan of drinking kombucha, painting, running, and programming.  (Not at the same time.)"
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname: rdxiang


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
